// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACUQGT-KC0ijfrHncU6cFPU6GjinLent0',
    appId: '1:351080144491:web:1b954bf84f99e2ab619b2e',
    messagingSenderId: '351080144491',
    projectId: 'language-learning-applic-9b0f3',
    authDomain: 'language-learning-applic-9b0f3.firebaseapp.com',
    storageBucket: 'language-learning-applic-9b0f3.firebasestorage.app',
    measurementId: 'G-R61MV1WQXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2LvBVfvDtgbPZrsFSIgLsdPsioYxUMg',
    appId: '1:351080144491:android:b7d1e6d02b954aeb619b2e',
    messagingSenderId: '351080144491',
    projectId: 'language-learning-applic-9b0f3',
    storageBucket: 'language-learning-applic-9b0f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5IhXivkADEz5AdEI4rqe9iYMwAsV6Plw',
    appId: '1:351080144491:ios:acdd16f98c35e218619b2e',
    messagingSenderId: '351080144491',
    projectId: 'language-learning-applic-9b0f3',
    storageBucket: 'language-learning-applic-9b0f3.firebasestorage.app',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5IhXivkADEz5AdEI4rqe9iYMwAsV6Plw',
    appId: '1:351080144491:ios:acdd16f98c35e218619b2e',
    messagingSenderId: '351080144491',
    projectId: 'language-learning-applic-9b0f3',
    storageBucket: 'language-learning-applic-9b0f3.firebasestorage.app',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACUQGT-KC0ijfrHncU6cFPU6GjinLent0',
    appId: '1:351080144491:web:e45a97c8f57cc49f619b2e',
    messagingSenderId: '351080144491',
    projectId: 'language-learning-applic-9b0f3',
    authDomain: 'language-learning-applic-9b0f3.firebaseapp.com',
    storageBucket: 'language-learning-applic-9b0f3.firebasestorage.app',
    measurementId: 'G-81F6ZG9SF2',
  );
}
