import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:get/get.dart';
import 'package:flutter/material.dart';

class QuizController extends GetxController {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  var currentStep = 0.obs;
  var selectedLanguage = ''.obs;
  var selectedDifficulty = ''.obs;
  var totalQuestions = 0.obs;
  var currentQuestionIndex = 0.obs;
  var score = 0.obs;
  var selectedOption = (-1).obs;
  var isAnswered = false.obs;

  List<Map<String, dynamic>> quizData = [];

  final List<String> languages = [
    'English to Urdu', 'Urdu to English',
    'English to Spanish', 'Spanish to English',
    'English to French', 'French to English',
    'English to Chinese', 'Chinese to English',
    'English to Italian', 'Italian to English'
  ];

  final Map<String, int> difficulties = {
    'Basic': 15,
    'Medium': 30,
    'Hard': 50,
  };

  final Map<String, List<Map<String, dynamic>>> questionBank = {
    'English to Urdu': [
      {'question': 'Water', 'options': ['Pani', 'Aag', 'Hawa', 'Mitti'], 'correctIndex': 0},
      {'question': 'Book', 'options': ['Kalam', 'Kitab', 'Basta', 'Mez'], 'correctIndex': 1},
      {'question': 'House', 'options': ['Dukan', 'Daftar', 'Ghar', 'Bazar'], 'correctIndex': 2},
      {'question': 'Sun', 'options': ['Chand', 'Sitara', 'Aasman', 'Suraj'], 'correctIndex': 3},
      {'question': 'Friend', 'options': ['Dost', 'Dushman', 'Bhai', 'Parosi'], 'correctIndex': 0},
      {'question': 'Apple', 'options': ['Aam', 'Kaila', 'Saib', 'Angoor'], 'correctIndex': 2},
      {'question': 'School', 'options': ['Madrassa', 'School', 'Dukan', 'Ghar'], 'correctIndex': 1},
      {'question': 'Car', 'options': ['Bus', 'Gari', 'Cycle', 'Jahaz'], 'correctIndex': 1},
      {'question': 'Night', 'options': ['Subah', 'Din', 'Raat', 'Shaam'], 'correctIndex': 2},
      {'question': 'Day', 'options': ['Din', 'Raat', 'Shaam', 'Subah'], 'correctIndex': 0},
      {'question': 'Milk', 'options': ['Doodh', 'Dahi', 'Makkhan', 'Lassi'], 'correctIndex': 0},
      {'question': 'Tree', 'options': ['Phool', 'Patta', 'Darakht', 'Tehni'], 'correctIndex': 2},
      {'question': 'Flower', 'options': ['Gulab', 'Phool', 'Chambeli', 'Kanwal'], 'correctIndex': 1},
      {'question': 'Chair', 'options': ['Mez', 'Kursi', 'Takht', 'Sofa'], 'correctIndex': 1},
      {'question': 'Table', 'options': ['Kursi', 'Mez', 'Almari', 'Bistar'], 'correctIndex': 1},
      {'question': 'Bird', 'options': ['Parinda', 'Janwar', 'Machli', 'Keera'], 'correctIndex': 0},
      {'question': 'Fish', 'options': ['Parinda', 'Machli', 'Mendak', 'Kachwa'], 'correctIndex': 1},
      {'question': 'Cat', 'options': ['Kutta', 'Billi', 'Sher', 'Cheeta'], 'correctIndex': 1},
      {'question': 'Dog', 'options': ['Billi', 'Kutta', 'Bheria', 'Lomri'], 'correctIndex': 1},
      {'question': 'Lion', 'options': ['Billi', 'Sher', 'Hathi', 'Ghora'], 'correctIndex': 1},
      {'question': 'Horse', 'options': ['Gadda', 'Ghora', 'Oont', 'Bakri'], 'correctIndex': 1},
      {'question': 'Camel', 'options': ['Bakri', 'Oont', 'Gai', 'Bhains'], 'correctIndex': 1},
      {'question': 'Mountain', 'options': ['Darya', 'Pahar', 'Maidan', 'Sehra'], 'correctIndex': 1},
      {'question': 'River', 'options': ['Samundar', 'Darya', 'Nala', 'Nehar'], 'correctIndex': 1},
      {'question': 'Sea', 'options': ['Darya', 'Samundar', 'Jheel', 'Chashma'], 'correctIndex': 1},
      {'question': 'Sky', 'options': ['Zameen', 'Aasman', 'Sitare', 'Baadal'], 'correctIndex': 1},
      {'question': 'Rain', 'options': ['Dhoop', 'Baarish', 'Olay', 'Barf'], 'correctIndex': 1},
      {'question': 'Fire', 'options': ['Pani', 'Aag', 'Dhuwan', 'Koyla'], 'correctIndex': 1},
      {'question': 'Earth', 'options': ['Aasman', 'Zameen', 'Sitare', 'Sayara'], 'correctIndex': 1},
      {'question': 'Moon', 'options': ['Suraj', 'Chand', 'Sitara', 'Zameen'], 'correctIndex': 1},
      {'question': 'Star', 'options': ['Chand', 'Sitara', 'Suraj', 'Sayara'], 'correctIndex': 1},
      {'question': 'City', 'options': ['Gao', 'Shehar', 'Qasba', 'Mohalla'], 'correctIndex': 1},
      {'question': 'Village', 'options': ['Shehar', 'Gao', 'Dunya', 'Mulk'], 'correctIndex': 1},
      {'question': 'Country', 'options': ['Shehar', 'Mulk', 'Soba', 'Zila'], 'correctIndex': 1},
      {'question': 'Road', 'options': ['Gali', 'Sarak', 'Rasta', 'Pugdandi'], 'correctIndex': 1},
      {'question': 'Door', 'options': ['Khidki', 'Darwaza', 'Deewar', 'Chat'], 'correctIndex': 1},
      {'question': 'Window', 'options': ['Darwaza', 'Khidki', 'Roshandan', 'Chat'], 'correctIndex': 1},
      {'question': 'Pencil', 'options': ['Kalam', 'Pencil', 'Siyahi', 'Kaghaz'], 'correctIndex': 1},
      {'question': 'Paper', 'options': ['Kalam', 'Kaghaz', 'Kitab', 'Daftar'], 'correctIndex': 1},
      {'question': 'Hand', 'options': ['Pao', 'Haath', 'Ungli', 'Bazu'], 'correctIndex': 1},
      {'question': 'Foot', 'options': ['Haath', 'Pao', 'Taanj', 'Ghutna'], 'correctIndex': 1},
      {'question': 'Eye', 'options': ['Naak', 'Aankh', 'Kaan', 'Mun'], 'correctIndex': 1},
      {'question': 'Nose', 'options': ['Aankh', 'Naak', 'Kaan', 'Mun'], 'correctIndex': 1},
      {'question': 'Ear', 'options': ['Naak', 'Kaan', 'Aankh', 'Mun'], 'correctIndex': 1},
      {'question': 'Mouth', 'options': ['Naak', 'Mun', 'Aankh', 'Dant'], 'correctIndex': 1},
      {'question': 'Tooth', 'options': ['Zuban', 'Dant', 'Hont', 'Mun'], 'correctIndex': 1},
      {'question': 'Tongue', 'options': ['Dant', 'Zuban', 'Mun', 'Hont'], 'correctIndex': 1},
      {'question': 'Head', 'options': ['Haath', 'Sar', 'Pao', 'Bazu'], 'correctIndex': 1},
      {'question': 'Hair', 'options': ['Sar', 'Baal', 'Aankh', 'Naak'], 'correctIndex': 1},
      {'question': 'Bread', 'options': ['Salad', 'Roti', 'Chawal', 'Doodh'], 'correctIndex': 1},
    ],
    'Urdu to English': [
      {'question': 'Pani', 'options': ['Fire', 'Water', 'Air', 'Sky'], 'correctIndex': 1},
      {'question': 'Kitab', 'options': ['Pen', 'Pencil', 'Book', 'Bag'], 'correctIndex': 2},
      {'question': 'Suraj', 'options': ['Moon', 'Sun', 'Star', 'Cloud'], 'correctIndex': 1},
      {'question': 'Ghar', 'options': ['Office', 'Shop', 'House', 'School'], 'correctIndex': 2},
      {'question': 'Dost', 'options': ['Enemy', 'Friend', 'Brother', 'Neighbor'], 'correctIndex': 1},
      {'question': 'Saib', 'options': ['Banana', 'Mango', 'Apple', 'Orange'], 'correctIndex': 2},
      {'question': 'Gari', 'options': ['Bus', 'Car', 'Bike', 'Cycle'], 'correctIndex': 1},
      {'question': 'Darakht', 'options': ['Flower', 'Leaf', 'Tree', 'Branch'], 'correctIndex': 2},
      {'question': 'Raat', 'options': ['Morning', 'Day', 'Night', 'Evening'], 'correctIndex': 2},
      {'question': 'Din', 'options': ['Day', 'Night', 'Evening', 'Morning'], 'correctIndex': 0},
      {'question': 'Doodh', 'options': ['Milk', 'Curd', 'Butter', 'Cheese'], 'correctIndex': 0},
      {'question': 'Phool', 'options': ['Fruit', 'Flower', 'Seed', 'Root'], 'correctIndex': 1},
      {'question': 'Kursi', 'options': ['Table', 'Chair', 'Bed', 'Sofa'], 'correctIndex': 1},
      {'question': 'Mez', 'options': ['Chair', 'Table', 'Shelf', 'Desk'], 'correctIndex': 1},
      {'question': 'Parinda', 'options': ['Bird', 'Animal', 'Fish', 'Insect'], 'correctIndex': 0},
      {'question': 'Machli', 'options': ['Bird', 'Fish', 'Frog', 'Snake'], 'correctIndex': 1},
      {'question': 'Billi', 'options': ['Dog', 'Cat', 'Lion', 'Tiger'], 'correctIndex': 1},
      {'question': 'Kutta', 'options': ['Cat', 'Dog', 'Wolf', 'Fox'], 'correctIndex': 1},
      {'question': 'Sher', 'options': ['Cat', 'Lion', 'Elephant', 'Horse'], 'correctIndex': 1},
      {'question': 'Ghora', 'options': ['Donkey', 'Horse', 'Camel', 'Goat'], 'correctIndex': 1},
      {'question': 'Oont', 'options': ['Goat', 'Camel', 'Cow', 'Buffalo'], 'correctIndex': 1},
      {'question': 'Pahar', 'options': ['River', 'Mountain', 'Plain', 'Desert'], 'correctIndex': 1},
      {'question': 'Darya', 'options': ['Sea', 'River', 'Drain', 'Canal'], 'correctIndex': 1},
      {'question': 'Samundar', 'options': ['River', 'Ocean', 'Lake', 'Spring'], 'correctIndex': 1},
      {'question': 'Aasman', 'options': ['Earth', 'Sky', 'Stars', 'Clouds'], 'correctIndex': 1},
      {'question': 'Baarish', 'options': ['Sun', 'Rain', 'Hail', 'Snow'], 'correctIndex': 1},
      {'question': 'Aag', 'options': ['Water', 'Fire', 'Smoke', 'Coal'], 'correctIndex': 1},
      {'question': 'Zameen', 'options': ['Sky', 'Earth', 'Stars', 'Planet'], 'correctIndex': 1},
      {'question': 'Chand', 'options': ['Sun', 'Moon', 'Star', 'Earth'], 'correctIndex': 1},
      {'question': 'Sitara', 'options': ['Moon', 'Star', 'Sun', 'Planet'], 'correctIndex': 1},
      {'question': 'Shehar', 'options': ['Village', 'City', 'Town', 'Street'], 'correctIndex': 1},
      {'question': 'Gao', 'options': ['City', 'Village', 'World', 'Country'], 'correctIndex': 1},
      {'question': 'Mulk', 'options': ['City', 'Country', 'State', 'District'], 'correctIndex': 1},
      {'question': 'Sarak', 'options': ['Lane', 'Road', 'Path', 'Track'], 'correctIndex': 1},
      {'question': 'Darwaza', 'options': ['Window', 'Door', 'Wall', 'Roof'], 'correctIndex': 1},
      {'question': 'Khidki', 'options': ['Door', 'Window', 'Vent', 'Roof'], 'correctIndex': 1},
      {'question': 'Pencil', 'options': ['Pen', 'Pencil', 'Ink', 'Paper'], 'correctIndex': 1},
      {'question': 'Kaghaz', 'options': ['Pen', 'Paper', 'Book', 'Office'], 'correctIndex': 1},
      {'question': 'Haath', 'options': ['Foot', 'Hand', 'Finger', 'Arm'], 'correctIndex': 1},
      {'question': 'Pao', 'options': ['Hand', 'Foot', 'Leg', 'Knee'], 'correctIndex': 1},
      {'question': 'Aankh', 'options': ['Nose', 'Eye', 'Ear', 'Mouth'], 'correctIndex': 1},
      {'question': 'Naak', 'options': ['Eye', 'Nose', 'Ear', 'Mouth'], 'correctIndex': 1},
      {'question': 'Kaan', 'options': ['Nose', 'Ear', 'Eye', 'Mouth'], 'correctIndex': 1},
      {'question': 'Mun', 'options': ['Nose', 'Mouth', 'Eye', 'Teeth'], 'correctIndex': 1},
      {'question': 'Dant', 'options': ['Tongue', 'Tooth', 'Lip', 'Mouth'], 'correctIndex': 1},
      {'question': 'Zuban', 'options': ['Tooth', 'Tongue', 'Mouth', 'Lip'], 'correctIndex': 1},
      {'question': 'Sar', 'options': ['Hand', 'Head', 'Foot', 'Arm'], 'correctIndex': 1},
      {'question': 'Baal', 'options': ['Head', 'Hair', 'Eye', 'Nose'], 'correctIndex': 1},
      {'question': 'Roti', 'options': ['Salad', 'Bread', 'Rice', 'Milk'], 'correctIndex': 1},
      {'question': 'Chawal', 'options': ['Bread', 'Rice', 'Wheat', 'Corn'], 'correctIndex': 1},
    ],
    'English to Spanish': [
      {'question': 'Hello', 'options': ['Adiós', 'Hola', 'Gracias', 'Perdón'], 'correctIndex': 1},
      {'question': 'Thank you', 'options': ['De nada', 'Gracias', 'Hola', 'Sí'], 'correctIndex': 1},
      {'question': 'Bread', 'options': ['Agua', 'Leche', 'Pan', 'Vino'], 'correctIndex': 2},
      {'question': 'Water', 'options': ['Fuego', 'Agua', 'Tierra', 'Aire'], 'correctIndex': 1},
      {'question': 'Good', 'options': ['Malo', 'Bueno', 'Grande', 'Pequeño'], 'correctIndex': 1},
      {'question': 'Boy', 'options': ['Niña', 'Niño', 'Hombre', 'Mujer'], 'correctIndex': 1},
      {'question': 'Girl', 'options': ['Niño', 'Niña', 'Mujer', 'Hombre'], 'correctIndex': 1},
      {'question': 'Man', 'options': ['Mujer', 'Hombre', 'Niño', 'Niña'], 'correctIndex': 1},
      {'question': 'Woman', 'options': ['Hombre', 'Mujer', 'Niña', 'Niño'], 'correctIndex': 1},
      {'question': 'Father', 'options': ['Madre', 'Padre', 'Hijo', 'Hija'], 'correctIndex': 1},
      {'question': 'Mother', 'options': ['Padre', 'Madre', 'Hija', 'Hijo'], 'correctIndex': 1},
      {'question': 'Son', 'options': ['Hija', 'Hijo', 'Hermano', 'Hermana'], 'correctIndex': 1},
      {'question': 'Daughter', 'options': ['Hijo', 'Hija', 'Hermana', 'Hermano'], 'correctIndex': 1},
      {'question': 'Brother', 'options': ['Hermana', 'Hermano', 'Amigo', 'Primo'], 'correctIndex': 1},
      {'question': 'Sister', 'options': ['Hermano', 'Hermana', 'Amiga', 'Prima'], 'correctIndex': 1},
      {'question': 'Friend', 'options': ['Enemigo', 'Amigo', 'Socio', 'Vecino'], 'correctIndex': 1},
      {'question': 'House', 'options': ['Escuela', 'Casa', 'Tienda', 'Oficina'], 'correctIndex': 1},
      {'question': 'School', 'options': ['Casa', 'Escuela', 'Parque', 'Calle'], 'correctIndex': 1},
      {'question': 'Book', 'options': ['Lápiz', 'Libro', 'Papel', 'Mesa'], 'correctIndex': 1},
      {'question': 'Pen', 'options': ['Libro', 'Bolígrafo', 'Silla', 'Cama'], 'correctIndex': 1},
      {'question': 'City', 'options': ['Pueblo', 'Ciudad', 'País', 'Mundo'], 'correctIndex': 1},
      {'question': 'Street', 'options': ['Camino', 'Calle', 'Plaza', 'Puente'], 'correctIndex': 1},
      {'question': 'Car', 'options': ['Bici', 'Coche', 'Bus', 'Tren'], 'correctIndex': 1},
      {'question': 'Dog', 'options': ['Gato', 'Perro', 'Pájaro', 'Pez'], 'correctIndex': 1},
      {'question': 'Cat', 'options': ['Perro', 'Gato', 'Ratón', 'Conejo'], 'correctIndex': 1},
      {'question': 'Bird', 'options': ['Pez', 'Pájaro', 'Insecto', 'León'], 'correctIndex': 1},
      {'question': 'Day', 'options': ['Noche', 'Día', 'Tarde', 'Mañana'], 'correctIndex': 1},
      {'question': 'Night', 'options': ['Día', 'Noche', 'Semana', 'Mes'], 'correctIndex': 1},
      {'question': 'Morning', 'options': ['Tarde', 'Mañana', 'Noche', 'Hoy'], 'correctIndex': 1},
      {'question': 'Evening', 'options': ['Mañana', 'Tarde', 'Noche', 'Ayer'], 'correctIndex': 1},
      {'question': 'Red', 'options': ['Azul', 'Rojo', 'Verde', 'Amarillo'], 'correctIndex': 1},
      {'question': 'Blue', 'options': ['Rojo', 'Azul', 'Blanco', 'Negro'], 'correctIndex': 1},
      {'question': 'Green', 'options': ['Amarillo', 'Verde', 'Rojo', 'Naranja'], 'correctIndex': 1},
      {'question': 'Sun', 'options': ['Luna', 'Sol', 'Estrella', 'Nube'], 'correctIndex': 1},
      {'question': 'Moon', 'options': ['Sol', 'Luna', 'Cielo', 'Mar'], 'correctIndex': 1},
      {'question': 'Love', 'options': ['Odio', 'Amor', 'Paz', 'Guerra'], 'correctIndex': 1},
      {'question': 'Life', 'options': ['Muerte', 'Vida', 'Tiempo', 'Dinero'], 'correctIndex': 1},
      {'question': 'Happy', 'options': ['Triste', 'Feliz', 'Enojado', 'Cansado'], 'correctIndex': 1},
      {'question': 'Sad', 'options': ['Feliz', 'Triste', 'Fuerte', 'Débil'], 'correctIndex': 1},
      {'question': 'Work', 'options': ['Juego', 'Trabajo', 'Sueño', 'Comida'], 'correctIndex': 1},
      {'question': 'Food', 'options': ['Bebida', 'Comida', 'Fruta', 'Carne'], 'correctIndex': 1},
      {'question': 'Money', 'options': ['Pobre', 'Dinero', 'Oro', 'Rico'], 'correctIndex': 1},
      {'question': 'Time', 'options': ['Reloj', 'Tiempo', 'Hora', 'Día'], 'correctIndex': 1},
      {'question': 'Always', 'options': ['Nunca', 'Siempre', 'A veces', 'Hoy'], 'correctIndex': 1},
      {'question': 'Never', 'options': ['Siempre', 'Nunca', 'Quizás', 'Ahora'], 'correctIndex': 1},
      {'question': 'Yes', 'options': ['No', 'Sí', 'Bueno', 'Hola'], 'correctIndex': 1},
      {'question': 'No', 'options': ['Sí', 'No', 'Gracias', 'Adiós'], 'correctIndex': 1},
      {'question': 'Please', 'options': ['Gracias', 'Por favor', 'Perdón', 'Hola'], 'correctIndex': 1},
      {'question': 'Sorry', 'options': ['Gracias', 'Lo siento', 'Hola', 'Adiós'], 'correctIndex': 1},
      {'question': 'Goodbye', 'options': ['Hola', 'Adiós', 'Hasta luego', 'Buenos días'], 'correctIndex': 1},
    ],
    'Spanish to English': [
      {'question': 'Hola', 'options': ['Goodbye', 'Hello', 'Thanks', 'Sorry'], 'correctIndex': 1},
      {'question': 'Gracias', 'options': ['Please', 'Thank you', 'Yes', 'No'], 'correctIndex': 1},
      {'question': 'Casa', 'options': ['School', 'House', 'Car', 'Street'], 'correctIndex': 1},
      {'question': 'Perro', 'options': ['Cat', 'Dog', 'Bird', 'Fish'], 'correctIndex': 1},
      {'question': 'Gato', 'options': ['Dog', 'Cat', 'Mouse', 'Lion'], 'correctIndex': 1},
      {'question': 'Pan', 'options': ['Milk', 'Bread', 'Water', 'Wine'], 'correctIndex': 1},
      {'question': 'Agua', 'options': ['Fire', 'Water', 'Earth', 'Air'], 'correctIndex': 1},
      {'question': 'Sol', 'options': ['Moon', 'Sun', 'Star', 'Sky'], 'correctIndex': 1},
      {'question': 'Luna', 'options': ['Sun', 'Moon', 'Planet', 'Cloud'], 'correctIndex': 1},
      {'question': 'Niño', 'options': ['Girl', 'Boy', 'Man', 'Woman'], 'correctIndex': 1},
      {'question': 'Niña', 'options': ['Boy', 'Girl', 'Woman', 'Man'], 'correctIndex': 1},
      {'question': 'Hombre', 'options': ['Woman', 'Man', 'Father', 'Brother'], 'correctIndex': 1},
      {'question': 'Mujer', 'options': ['Man', 'Woman', 'Mother', 'Sister'], 'correctIndex': 1},
      {'question': 'Padre', 'options': ['Mother', 'Father', 'Son', 'Uncle'], 'correctIndex': 1},
      {'question': 'Madre', 'options': ['Father', 'Mother', 'Daughter', 'Aunt'], 'correctIndex': 1},
      {'question': 'Hermano', 'options': ['Sister', 'Brother', 'Friend', 'Cousin'], 'correctIndex': 1},
      {'question': 'Hermana', 'options': ['Brother', 'Sister', 'Friend', 'Cousin'], 'correctIndex': 1},
      {'question': 'Amigo', 'options': ['Enemy', 'Friend', 'Neighbor', 'Teacher'], 'correctIndex': 1},
      {'question': 'Escuela', 'options': ['Work', 'School', 'Market', 'Church'], 'correctIndex': 1},
      {'question': 'Libro', 'options': ['Pen', 'Book', 'Paper', 'Table'], 'correctIndex': 1},
      {'question': 'Papel', 'options': ['Book', 'Paper', 'Pencil', 'Ink'], 'correctIndex': 1},
      {'question': 'Ciudad', 'options': ['Village', 'City', 'Country', 'State'], 'correctIndex': 1},
      {'question': 'Calle', 'options': ['Road', 'Street', 'Lane', 'Bridge'], 'correctIndex': 1},
      {'question': 'Coche', 'options': ['Bike', 'Car', 'Bus', 'Train'], 'correctIndex': 1},
      {'question': 'Día', 'options': ['Night', 'Day', 'Week', 'Month'], 'correctIndex': 1},
      {'question': 'Noche', 'options': ['Day', 'Night', 'Today', 'Yesterday'], 'correctIndex': 1},
      {'question': 'Hoy', 'options': ['Tomorrow', 'Today', 'Now', 'Always'], 'correctIndex': 1},
      {'question': 'Mañana', 'options': ['Yesterday', 'Tomorrow', 'Morning', 'Today'], 'correctIndex': 1},
      {'question': 'Rojo', 'options': ['Blue', 'Red', 'Green', 'Yellow'], 'correctIndex': 1},
      {'question': 'Azul', 'options': ['Red', 'Blue', 'White', 'Black'], 'correctIndex': 1},
      {'question': 'Verde', 'options': ['Yellow', 'Green', 'Orange', 'Grey'], 'correctIndex': 1},
      {'question': 'Blanco', 'options': ['Black', 'White', 'Pink', 'Purple'], 'correctIndex': 1},
      {'question': 'Negro', 'options': ['White', 'Black', 'Brown', 'Gold'], 'correctIndex': 1},
      {'question': 'Feliz', 'options': ['Sad', 'Happy', 'Angry', 'Tired'], 'correctIndex': 1},
      {'question': 'Triste', 'options': ['Happy', 'Sad', 'Strong', 'Weak'], 'correctIndex': 1},
      {'question': 'Amor', 'options': ['Hate', 'Love', 'Peace', 'War'], 'correctIndex': 1},
      {'question': 'Vida', 'options': ['Death', 'Life', 'Time', 'Age'], 'correctIndex': 1},
      {'question': 'Tiempo', 'options': ['Clock', 'Time', 'Day', 'Year'], 'correctIndex': 1},
      {'question': 'Dinero', 'options': ['Work', 'Money', 'Gold', 'Rich'], 'correctIndex': 1},
      {'question': 'Trabajo', 'options': ['Play', 'Work', 'Rest', 'Job'], 'correctIndex': 1},
      {'question': 'Comida', 'options': ['Drink', 'Food', 'Eat', 'Fruit'], 'correctIndex': 1},
      {'question': 'Sì', 'options': ['No', 'Yes', 'Maybe', 'Always'], 'correctIndex': 1},
      {'question': 'No', 'options': ['Yes', 'No', 'Never', 'Always'], 'correctIndex': 1},
      {'question': 'Siempre', 'options': ['Never', 'Always', 'Sometimes', 'Today'], 'correctIndex': 1},
      {'question': 'Nunca', 'options': ['Always', 'Never', 'Perhaps', 'Later'], 'correctIndex': 1},
      {'question': 'Por favor', 'options': ['Thanks', 'Please', 'Sorry', 'Hello'], 'correctIndex': 1},
      {'question': 'Lo siento', 'options': ['Thanks', 'I am sorry', 'Hello', 'Goodbye'], 'correctIndex': 1},
      {'question': 'Adiós', 'options': ['Hello', 'Goodbye', 'Good night', 'Later'], 'correctIndex': 1},
      {'question': 'Malo', 'options': ['Good', 'Bad', 'Big', 'Small'], 'correctIndex': 1},
      {'question': 'Bueno', 'options': ['Bad', 'Good', 'Better', 'Best'], 'correctIndex': 1},
    ],
    'English to French': [
      {'question': 'Hello', 'options': ['Au revoir', 'Bonjour', 'Merci', 'Oui'], 'correctIndex': 1},
      {'question': 'Thank you', 'options': ['Pardon', 'Merci', 'S\'il vous plaît', 'Salut'], 'correctIndex': 1},
      {'question': 'Yes', 'options': ['Non', 'Oui', 'Peut-être', 'Jamais'], 'correctIndex': 1},
      {'question': 'No', 'options': ['Oui', 'Non', 'Pas du tout', 'Toujours'], 'correctIndex': 1},
      {'question': 'Water', 'options': ['Feu', 'Eau', 'Air', 'Terre'], 'correctIndex': 1},
      {'question': 'Bread', 'options': ['Lait', 'Pain', 'Vin', 'Fromage'], 'correctIndex': 1},
      {'question': 'Friend', 'options': ['Ennemi', 'Ami', 'Voisin', 'Frère'], 'correctIndex': 1},
      {'question': 'House', 'options': ['École', 'Maison', 'Voiture', 'Ville'], 'correctIndex': 1},
      {'question': 'School', 'options': ['Maison', 'École', 'Parc', 'Dortoir'], 'correctIndex': 1},
      {'question': 'Book', 'options': ['Stylo', 'Livre', 'Papier', 'Table'], 'correctIndex': 1},
      {'question': 'Love', 'options': ['Haine', 'Amour', 'Paix', 'Joie'], 'correctIndex': 1},
      {'question': 'Life', 'options': ['Mort', 'Vie', 'Temps', 'Monde'], 'correctIndex': 1},
      {'question': 'Sun', 'options': ['Lune', 'Soleil', 'Étoile', 'Ciel'], 'correctIndex': 1},
      {'question': 'Moon', 'options': ['Soleil', 'Lune', 'Nuage', 'Mer'], 'correctIndex': 1},
      {'question': 'Day', 'options': ['Nuit', 'Jour', 'Semaine', 'Mois'], 'correctIndex': 1},
      {'question': 'Night', 'options': ['Jour', 'Nuit', 'Soir', 'Matin'], 'correctIndex': 1},
      {'question': 'Boy', 'options': ['Fille', 'Garçon', 'Homme', 'Femme'], 'correctIndex': 1},
      {'question': 'Girl', 'options': ['Garçon', 'Fille', 'Mère', 'Soeur'], 'correctIndex': 1},
      {'question': 'Man', 'options': ['Femme', 'Homme', 'Père', 'Roi'], 'correctIndex': 1},
      {'question': 'Woman', 'options': ['Homme', 'Femme', 'Mère', 'Reine'], 'correctIndex': 1},
      {'question': 'Father', 'options': ['Mère', 'Père', 'Fils', 'Oncle'], 'correctIndex': 1},
      {'question': 'Mother', 'options': ['Père', 'Mère', 'Fille', 'Tante'], 'correctIndex': 1},
      {'question': 'Work', 'options': ['Jeu', 'Travail', 'Sommeil', 'Repos'], 'correctIndex': 1},
      {'question': 'Money', 'options': ['Pauvre', 'Argent', 'Or', 'Banque'], 'correctIndex': 1},
      {'question': 'Red', 'options': ['Bleu', 'Rouge', 'Vert', 'Jaune'], 'correctIndex': 1},
      {'question': 'Blue', 'options': ['Rouge', 'Bleu', 'Blanc', 'Noir'], 'correctIndex': 1},
      {'question': 'Green', 'options': ['Jaune', 'Vert', 'Gris', 'Marron'], 'correctIndex': 1},
      {'question': 'White', 'options': ['Noir', 'Blanc', 'Rose', 'Violet'], 'correctIndex': 1},
      {'question': 'Black', 'options': ['Blanc', 'Noir', 'Orange', 'Or'], 'correctIndex': 1},
      {'question': 'City', 'options': ['Village', 'Ville', 'Pays', 'Rue'], 'correctIndex': 1},
      {'question': 'Car', 'options': ['Vélo', 'Voiture', 'Bus', 'Train'], 'correctIndex': 1},
      {'question': 'Dog', 'options': ['Chat', 'Chien', 'Oiseau', 'Poisson'], 'correctIndex': 1},
      {'question': 'Cat', 'options': ['Chien', 'Chat', 'Souris', 'Lapin'], 'correctIndex': 1},
      {'question': 'Time', 'options': ['Heure', 'Temps', 'Jour', 'An'], 'correctIndex': 1},
      {'question': 'Happy', 'options': ['Triste', 'Heureux', 'Fâché', 'Calme'], 'correctIndex': 1},
      {'question': 'Sad', 'options': ['Heureux', 'Triste', 'Fort', 'Faible'], 'correctIndex': 1},
      {'question': 'Good', 'options': ['Mauvais', 'Bon', 'Grand', 'Petit'], 'correctIndex': 1},
      {'question': 'Bad', 'options': ['Bon', 'Mauvais', 'Mieux', 'Pire'], 'correctIndex': 1},
      {'question': 'Small', 'options': ['Grand', 'Petit', 'Léger', 'Court'], 'correctIndex': 1},
      {'question': 'Big', 'options': ['Petit', 'Grand', 'Lourd', 'Long'], 'correctIndex': 1},
      {'question': 'Beautiful', 'options': ['Laid', 'Beau', 'Jeune', 'Vieux'], 'correctIndex': 1},
      {'question': 'Ugly', 'options': ['Beau', 'Laid', 'Sale', 'Propre'], 'correctIndex': 1},
      {'question': 'Always', 'options': ['Jamais', 'Toujours', 'Parfois', 'Souvent'], 'correctIndex': 1},
      {'question': 'Never', 'options': ['Toujours', 'Jamais', 'Peut-être', 'Bientôt'], 'correctIndex': 1},
      {'question': 'Please', 'options': ['Merci', 'S\'il vous plaît', 'Désolé', 'Salut'], 'correctIndex': 1},
      {'question': 'Sorry', 'options': ['Merci', 'Désolé', 'Bonjour', 'Pardon'], 'correctIndex': 1},
      {'question': 'Goodbye', 'options': ['Bonjour', 'Au revoir', 'À demain', 'Salut'], 'correctIndex': 1},
      {'question': 'Eat', 'options': ['Boire', 'Manger', 'Dormir', 'Courir'], 'correctIndex': 1},
      {'question': 'Drink', 'options': ['Manger', 'Boire', 'Lire', 'Écrire'], 'correctIndex': 1},
      {'question': 'Sleep', 'options': ['Travailler', 'Dormir', 'Rêver', 'Se lever'], 'correctIndex': 1},
    ],
    // Baqi 5 Pairs (French to English, Chinese, Italian) ke liye bhi isi pattern par 50 MCQs added hain
    'French to English': [
      {'question': 'Bonjour', 'options': ['Goodbye', 'Hello', 'Thanks', 'Yes'], 'correctIndex': 1},
      {'question': 'Merci', 'options': ['Please', 'Thank you', 'No', 'Sorry'], 'correctIndex': 1},
      {'question': 'Oui', 'options': ['No', 'Yes', 'Maybe', 'Never'], 'correctIndex': 1},
      {'question': 'Non', 'options': ['Yes', 'No', 'Always', 'Often'], 'correctIndex': 1},
      {'question': 'Eau', 'options': ['Fire', 'Water', 'Earth', 'Air'], 'correctIndex': 1},
      {'question': 'Pain', 'options': ['Milk', 'Bread', 'Cheese', 'Butter'], 'correctIndex': 1},
      {'question': 'Ami', 'options': ['Enemy', 'Friend', 'Brother', 'Sister'], 'correctIndex': 1},
      {'question': 'Maison', 'options': ['School', 'House', 'Car', 'City'], 'correctIndex': 1},
      {'question': 'École', 'options': ['House', 'School', 'Office', 'Park'], 'correctIndex': 1},
      {'question': 'Livre', 'options': ['Pen', 'Book', 'Paper', 'Notebook'], 'correctIndex': 1},
      {'question': 'Amour', 'options': ['Hate', 'Love', 'Peace', 'Joy'], 'correctIndex': 1},
      {'question': 'Vie', 'options': ['Death', 'Life', 'World', 'Age'], 'correctIndex': 1},
      {'question': 'Soleil', 'options': ['Moon', 'Sun', 'Star', 'Sky'], 'correctIndex': 1},
      {'question': 'Lune', 'options': ['Sun', 'Moon', 'Cloud', 'Ocean'], 'correctIndex': 1},
      {'question': 'Jour', 'options': ['Night', 'Day', 'Week', 'Year'], 'correctIndex': 1},
      {'question': 'Nuit', 'options': ['Day', 'Night', 'Evening', 'Morning'], 'correctIndex': 1},
      {'question': 'Garçon', 'options': ['Girl', 'Boy', 'Man', 'Woman'], 'correctIndex': 1},
      {'question': 'Fille', 'options': ['Boy', 'Girl', 'Mother', 'Aunt'], 'correctIndex': 1},
      {'question': 'Homme', 'options': ['Woman', 'Man', 'Father', 'King'], 'correctIndex': 1},
      {'question': 'Femme', 'options': ['Man', 'Woman', 'Mother', 'Queen'], 'correctIndex': 1},
      {'question': 'Père', 'options': ['Mother', 'Father', 'Son', 'Brother'], 'correctIndex': 1},
      {'question': 'Mère', 'options': ['Father', 'Mother', 'Daughter', 'Sister'], 'correctIndex': 1},
      {'question': 'Travail', 'options': ['Play', 'Work', 'Sleep', 'Rest'], 'correctIndex': 1},
      {'question': 'Argent', 'options': ['Gold', 'Money', 'Silver', 'Poor'], 'correctIndex': 1},
      {'question': 'Rouge', 'options': ['Blue', 'Red', 'Green', 'Yellow'], 'correctIndex': 1},
      {'question': 'Bleu', 'options': ['Red', 'Blue', 'White', 'Black'], 'correctIndex': 1},
      {'question': 'Vert', 'options': ['Yellow', 'Green', 'Grey', 'Brown'], 'correctIndex': 1},
      {'question': 'Blanc', 'options': ['Black', 'White', 'Pink', 'Purple'], 'correctIndex': 1},
      {'question': 'Noir', 'options': ['White', 'Black', 'Orange', 'Gold'], 'correctIndex': 1},
      {'question': 'Ville', 'options': ['Village', 'City', 'Country', 'Street'], 'correctIndex': 1},
      {'question': 'Voiture', 'options': ['Bike', 'Car', 'Bus', 'Train'], 'correctIndex': 1},
      {'question': 'Chien', 'options': ['Cat', 'Dog', 'Bird', 'Fish'], 'correctIndex': 1},
      {'question': 'Chat', 'options': ['Dog', 'Cat', 'Mouse', 'Rabbit'], 'correctIndex': 1},
      {'question': 'Temps', 'options': ['Hour', 'Time', 'Day', 'Year'], 'correctIndex': 1},
      {'question': 'Heureux', 'options': ['Sad', 'Happy', 'Angry', 'Quiet'], 'correctIndex': 1},
      {'question': 'Triste', 'options': ['Happy', 'Sad', 'Strong', 'Weak'], 'correctIndex': 1},
      {'question': 'Bon', 'options': ['Bad', 'Good', 'Better', 'Best'], 'correctIndex': 1},
      {'question': 'Mauvais', 'options': ['Good', 'Bad', 'Worst', 'Fine'], 'correctIndex': 1},
      {'question': 'Petit', 'options': ['Big', 'Small', 'Light', 'Short'], 'correctIndex': 1},
      {'question': 'Grand', 'options': ['Small', 'Big', 'Heavy', 'Long'], 'correctIndex': 1},
      {'question': 'Beau', 'options': ['Ugly', 'Beautiful', 'Young', 'Old'], 'correctIndex': 1},
      {'question': 'Laid', 'options': ['Beautiful', 'Ugly', 'Dirty', 'Clean'], 'correctIndex': 1},
      {'question': 'Toujours', 'options': ['Never', 'Always', 'Sometimes', 'Often'], 'correctIndex': 1},
      {'question': 'Jamais', 'options': ['Always', 'Never', 'Maybe', 'Soon'], 'correctIndex': 1},
      {'question': 'S\'il vous plaît', 'options': ['Thanks', 'Please', 'Sorry', 'Hello'], 'correctIndex': 1},
      {'question': 'Désolé', 'options': ['Thanks', 'Sorry', 'Hello', 'Pardon'], 'correctIndex': 1},
      {'question': 'Au revoir', 'options': ['Hello', 'Goodbye', 'See you', 'Hi'], 'correctIndex': 1},
      {'question': 'Manger', 'options': ['Drink', 'Eat', 'Sleep', 'Run'], 'correctIndex': 1},
      {'question': 'Boire', 'options': ['Eat', 'Drink', 'Read', 'Write'], 'correctIndex': 1},
      {'question': 'Dormir', 'options': ['Work', 'Sleep', 'Dream', 'Rise'], 'correctIndex': 1},
    ],
    'English to Chinese': [
      {'question': 'One', 'options': ['Er', 'Yi', 'San', 'Si'], 'correctIndex': 1},
      {'question': 'Two', 'options': ['Yi', 'Er', 'San', 'Si'], 'correctIndex': 1},
      {'question': 'Three', 'options': ['Er', 'San', 'Si', 'Wu'], 'correctIndex': 1},
      {'question': 'Hello', 'options': ['Ni hao', 'Xie xie', 'Zai jian', 'Dui bu qi'], 'correctIndex': 0},
      {'question': 'Thank you', 'options': ['Ni hao', 'Xie xie', 'Mei guan xi', 'Zai jian'], 'correctIndex': 1},
      {'question': 'Goodbye', 'options': ['Xie xie', 'Zai jian', 'Bu ke qi', 'Ni hao'], 'correctIndex': 1},
      {'question': 'Water', 'options': ['Huo', 'Shui', 'Tu', 'Feng'], 'correctIndex': 1},
      {'question': 'Fire', 'options': ['Shui', 'Huo', 'Feng', 'Mu'], 'correctIndex': 1},
      {'question': 'Person', 'options': ['Ren', 'Shan', 'Tian', 'Di'], 'correctIndex': 0},
      {'question': 'Big', 'options': ['Xiao', 'Da', 'Duo', 'Shao'], 'correctIndex': 1},
      {'question': 'Small', 'options': ['Da', 'Xiao', 'Gao', 'Di'], 'correctIndex': 1},
      {'question': 'Good', 'options': ['Hao', 'Huai', 'Leng', 'Re'], 'correctIndex': 0},
      {'question': 'Bad', 'options': ['Hao', 'Huai', 'Ku', 'Tian'], 'correctIndex': 1},
      {'question': 'Sun', 'options': ['Yue', 'Ri', 'Xing', 'Yun'], 'correctIndex': 1},
      {'question': 'Moon', 'options': ['Ri', 'Yue', 'Shan', 'Shui'], 'correctIndex': 1},
      {'question': 'Mountain', 'options': ['Shui', 'Shan', 'Mu', 'Huo'], 'correctIndex': 1},
      {'question': 'Wood', 'options': ['Jin', 'Mu', 'Shui', 'Huo'], 'correctIndex': 1},
      {'question': 'Gold', 'options': ['Mu', 'Jin', 'Tu', 'Shui'], 'correctIndex': 1},
      {'question': 'Friend', 'options': ['Peng you', 'Lao shi', 'Xue sheng', 'Ba ba'], 'correctIndex': 0},
      {'question': 'Teacher', 'options': ['Xue sheng', 'Lao shi', 'Ma ma', 'Yi sheng'], 'correctIndex': 1},
      {'question': 'Student', 'options': ['Lao shi', 'Xue sheng', 'Peng you', 'Jia ren'], 'correctIndex': 1},
      {'question': 'Doctor', 'options': ['Hu shi', 'Yi sheng', 'Si ji', 'Gong ren'], 'correctIndex': 1},
      {'question': 'Father', 'options': ['Ma ma', 'Ba ba', 'Ge ge', 'Di di'], 'correctIndex': 1},
      {'question': 'Mother', 'options': ['Ba ba', 'Ma ma', 'Jie jie', 'Mei mei'], 'correctIndex': 1},
      {'question': 'Brother', 'options': ['Jie jie', 'Ge ge', 'Peng you', 'Ba ba'], 'correctIndex': 1},
      {'question': 'Sister', 'options': ['Ge ge', 'Jie jie', 'Ma ma', 'Peng you'], 'correctIndex': 1},
      {'question': 'Eat', 'options': ['He', 'Chi', 'Shui', 'Zou'], 'correctIndex': 1},
      {'question': 'Drink', 'options': ['Chi', 'He', 'Shuo', 'Du'], 'correctIndex': 1},
      {'question': 'Speak', 'options': ['Du', 'Shuo', 'Ting', 'Xie'], 'correctIndex': 1},
      {'question': 'Listen', 'options': ['Shuo', 'Ting', 'Xie', 'Du'], 'correctIndex': 1},
      {'question': 'Read', 'options': ['Xie', 'Du', 'Kan', 'Zou'], 'correctIndex': 1},
      {'question': 'Write', 'options': ['Du', 'Xie', 'Ting', 'Shuo'], 'correctIndex': 1},
      {'question': 'House', 'options': ['Che', 'Jia', 'Lu', 'Dian'], 'correctIndex': 1},
      {'question': 'Car', 'options': ['Jia', 'Che', 'Chuan', 'Fei ji'], 'correctIndex': 1},
      {'question': 'Today', 'options': ['Ming tian', 'Jin tian', 'Zuo tian', 'Xian zai'], 'correctIndex': 1},
      {'question': 'Tomorrow', 'options': ['Jin tian', 'Ming tian', 'Zuo tian', 'Jin wan'], 'correctIndex': 1},
      {'question': 'Yesterday', 'options': ['Jin tian', 'Zuo tian', 'Ming tian', 'Jin nian'], 'correctIndex': 1},
      {'question': 'Now', 'options': ['Deng xia', 'Xian zai', 'Yi qian', 'Yi hou'], 'correctIndex': 1},
      {'question': 'China', 'options': ['Mei guo', 'Zhong guo', 'Ri ben', 'Ying guo'], 'correctIndex': 1},
      {'question': 'America', 'options': ['Zhong guo', 'Mei guo', 'Fa guo', 'De guo'], 'correctIndex': 1},
      {'question': 'Fruit', 'options': ['Cai', 'Shui guo', 'Rou', 'Mian'], 'correctIndex': 1},
      {'question': 'Meat', 'options': ['Shui guo', 'Rou', 'Dan', 'Nai'], 'correctIndex': 1},
      {'question': 'Milk', 'options': ['Rou', 'Niu nai', 'Shui', 'Cha'], 'correctIndex': 1},
      {'question': 'Tea', 'options': ['Niu nai', 'Cha', 'Ka fei', 'Jiu'], 'correctIndex': 1},
      {'question': 'Red', 'options': ['Lan', 'Hong', 'Lv', 'Hei'], 'correctIndex': 1},
      {'question': 'Blue', 'options': ['Hong', 'Lan', 'Bai', 'Huang'], 'correctIndex': 1},
      {'question': 'Love', 'options': ['Hen', 'Ai', 'Xi huan', 'Xiang'], 'correctIndex': 1},
      {'question': 'Sky', 'options': ['Di', 'Tian', 'Yun', 'Yu'], 'correctIndex': 1},
      {'question': 'Earth', 'options': ['Tian', 'Di', 'Shan', 'He'], 'correctIndex': 1},
      {'question': 'Country', 'options': ['Cheng', 'Guo', 'Ren', 'Jia'], 'correctIndex': 1},
    ],
    'Chinese to English': [
      {'question': 'Yi', 'options': ['Two', 'One', 'Three', 'Four'], 'correctIndex': 1},
      {'question': 'Ni hao', 'options': ['Goodbye', 'Hello', 'Thanks', 'Please'], 'correctIndex': 1},
      {'question': 'Xie xie', 'options': ['Sorry', 'Thank you', 'Hello', 'Yes'], 'correctIndex': 1},
      {'question': 'Shui', 'options': ['Fire', 'Water', 'Wood', 'Gold'], 'correctIndex': 1},
      {'question': 'Ren', 'options': ['Dog', 'Person', 'Cat', 'Bird'], 'correctIndex': 1},
      {'question': 'Da', 'options': ['Small', 'Big', 'Long', 'Short'], 'correctIndex': 1},
      {'question': 'Xiao', 'options': ['Big', 'Small', 'High', 'Low'], 'correctIndex': 1},
      {'question': 'Hao', 'options': ['Bad', 'Good', 'New', 'Old'], 'correctIndex': 1},
      {'question': 'Ri', 'options': ['Moon', 'Sun', 'Star', 'Cloud'], 'correctIndex': 1},
      {'question': 'Yue', 'options': ['Sun', 'Moon', 'Sky', 'River'], 'correctIndex': 1},
      {'question': 'Shan', 'options': ['Sea', 'Mountain', 'Field', 'Forest'], 'correctIndex': 1},
      {'question': 'Ba ba', 'options': ['Mother', 'Father', 'Brother', 'Sister'], 'correctIndex': 1},
      {'question': 'Ma ma', 'options': ['Father', 'Mother', 'Aunt', 'Son'], 'correctIndex': 1},
      {'question': 'Chi', 'options': ['Drink', 'Eat', 'Sleep', 'Walk'], 'correctIndex': 1},
      {'question': 'He', 'options': ['Eat', 'Drink', 'Speak', 'Write'], 'correctIndex': 1},
      {'question': 'Jia', 'options': ['Car', 'House/Home', 'Road', 'School'], 'correctIndex': 1},
      {'question': 'Jin tian', 'options': ['Tomorrow', 'Today', 'Yesterday', 'Now'], 'correctIndex': 1},
      {'question': 'Ming tian', 'options': ['Today', 'Tomorrow', 'Yesterday', 'Next year'], 'correctIndex': 1},
      {'question': 'Zhong guo', 'options': ['Japan', 'China', 'America', 'Korea'], 'correctIndex': 1},
      {'question': 'Hong', 'options': ['Blue', 'Red', 'Green', 'Yellow'], 'correctIndex': 1},
      {'question': 'Lan', 'options': ['Red', 'Blue', 'White', 'Black'], 'correctIndex': 1},
      {'question': 'Ai', 'options': ['Hate', 'Love', 'Like', 'Want'], 'correctIndex': 1},
      {'question': 'Tian', 'options': ['Earth', 'Sky', 'Field', 'Water'], 'correctIndex': 1},
      {'question': 'Guo', 'options': ['Person', 'Country', 'City', 'Village'], 'correctIndex': 1},
      {'question': 'Xue sheng', 'options': ['Teacher', 'Student', 'Friend', 'Family'], 'correctIndex': 1},
      {'question': 'Lao shi', 'options': ['Student', 'Teacher', 'Doctor', 'Driver'], 'correctIndex': 1},
      {'question': 'Che', 'options': ['House', 'Car/Vehicle', 'Boat', 'Plane'], 'correctIndex': 1},
      {'question': 'Zai jian', 'options': ['Hello', 'Goodbye', 'Please', 'Sorry'], 'correctIndex': 1},
      {'question': 'Dui bu qi', 'options': ['Thanks', 'I am sorry', 'No problem', 'Hi'], 'correctIndex': 1},
      {'question': 'Mei guan xi', 'options': ['Sorry', 'It is okay', 'Wait', 'Stop'], 'correctIndex': 1},
      {'question': 'Er', 'options': ['One', 'Two', 'Three', 'Ten'], 'correctIndex': 1},
      {'question': 'San', 'options': ['Two', 'Three', 'Four', 'Five'], 'correctIndex': 1},
      {'question': 'Si', 'options': ['Three', 'Four', 'Five', 'Six'], 'correctIndex': 1},
      {'question': 'Wu', 'options': ['Four', 'Five', 'Six', 'Seven'], 'correctIndex': 1},
      {'question': 'Liu', 'options': ['Five', 'Six', 'Seven', 'Eight'], 'correctIndex': 1},
      {'question': 'Qi', 'options': ['Six', 'Seven', 'Eight', 'Nine'], 'correctIndex': 1},
      {'question': 'Ba', 'options': ['Seven', 'Eight', 'Nine', 'Ten'], 'correctIndex': 1},
      {'question': 'Jiu', 'options': ['Eight', 'Nine', 'Ten', 'Zero'], 'correctIndex': 1},
      {'question': 'Shi', 'options': ['Nine', 'Ten', 'One', 'Two'], 'correctIndex': 1},
      {'question': 'Shuo', 'options': ['Listen', 'Speak', 'Read', 'Write'], 'correctIndex': 1},
      {'question': 'Ting', 'options': ['Speak', 'Listen', 'Look', 'Walk'], 'correctIndex': 1},
      {'question': 'Kan', 'options': ['Listen', 'Look/See', 'Eat', 'Drink'], 'correctIndex': 1},
      {'question': 'Nan', 'options': ['Woman', 'Man', 'Child', 'Old'], 'correctIndex': 1},
      {'question': 'Nv', 'options': ['Man', 'Woman', 'Boy', 'Girl'], 'correctIndex': 1},
      {'question': 'Huo', 'options': ['Water', 'Fire', 'Wind', 'Earth'], 'correctIndex': 1},
      {'question': 'Mu', 'options': ['Gold', 'Wood', 'Water', 'Fire'], 'correctIndex': 1},
      {'question': 'Jin', 'options': ['Wood', 'Gold/Metal', 'Earth', 'Water'], 'correctIndex': 1},
      {'question': 'Tu', 'options': ['Water', 'Earth/Soil', 'Sky', 'Fire'], 'correctIndex': 1},
      {'question': 'Qing', 'options': ['Thanks', 'Please', 'Sorry', 'Hello'], 'correctIndex': 1},
      {'question': 'Mei', 'options': ['Ugly', 'Beautiful', 'Fast', 'Slow'], 'correctIndex': 1},
    ],
    'English to Italian': [
      {'question': 'Hello', 'options': ['Arrivederci', 'Ciao', 'Grazie', 'Prego'], 'correctIndex': 1},
      {'question': 'Thank you', 'options': ['Prego', 'Grazie', 'Ciao', 'Scusa'], 'correctIndex': 1},
      {'question': 'Yes', 'options': ['No', 'Sì', 'Forse', 'Bene'], 'correctIndex': 1},
      {'question': 'No', 'options': ['Sì', 'No', 'Mai', 'Sempre'], 'correctIndex': 1},
      {'question': 'Water', 'options': ['Fuoco', 'Acqua', 'Aria', 'Terra'], 'correctIndex': 1},
      {'question': 'Bread', 'options': ['Latte', 'Pane', 'Vino', 'Pasta'], 'correctIndex': 1},
      {'question': 'Friend', 'options': ['Nemico', 'Amico', 'Fratello', 'Sorella'], 'correctIndex': 1},
      {'question': 'House', 'options': ['Scuola', 'Casa', 'Città', 'Strada'], 'correctIndex': 1},
      {'question': 'Book', 'options': ['Penna', 'Libro', 'Foglio', 'Tavolo'], 'correctIndex': 1},
      {'question': 'Sun', 'options': ['Luna', 'Sole', 'Stella', 'Cielo'], 'correctIndex': 1},
      {'question': 'Moon', 'options': ['Sole', 'Luna', 'Pianeta', 'Mare'], 'correctIndex': 1},
      {'question': 'Day', 'options': ['Notte', 'Giorno', 'Settimana', 'Mese'], 'correctIndex': 1},
      {'question': 'Night', 'options': ['Giorno', 'Notte', 'Sera', 'Mattina'], 'correctIndex': 1},
      {'question': 'Boy', 'options': ['Ragazza', 'Ragazzo', 'Uomo', 'Donna'], 'correctIndex': 1},
      {'question': 'Girl', 'options': ['Ragazzo', 'Ragazza', 'Madre', 'Sorella'], 'correctIndex': 1},
      {'question': 'Man', 'options': ['Donna', 'Uomo', 'Padre', 'Re'], 'correctIndex': 1},
      {'question': 'Woman', 'options': ['Uomo', 'Donna', 'Madre', 'Regina'], 'correctIndex': 1},
      {'question': 'Father', 'options': ['Madre', 'Padre', 'Figlio', 'Zio'], 'correctIndex': 1},
      {'question': 'Mother', 'options': ['Padre', 'Madre', 'Figlia', 'Zia'], 'correctIndex': 1},
      {'question': 'Love', 'options': ['Odio', 'Amore', 'Pace', 'Cuore'], 'correctIndex': 1},
      {'question': 'Life', 'options': ['Morte', 'Vita', 'Tempo', 'Mondo'], 'correctIndex': 1},
      {'question': 'Red', 'options': ['Blu', 'Rosso', 'Verde', 'Giallo'], 'correctIndex': 1},
      {'question': 'Blue', 'options': ['Rosso', 'Blu', 'Bianco', 'Nero'], 'correctIndex': 1},
      {'question': 'Green', 'options': ['Giallo', 'Verde', 'Grigio', 'Marrone'], 'correctIndex': 1},
      {'question': 'White', 'options': ['Nero', 'Bianco', 'Rosa', 'Viola'], 'correctIndex': 1},
      {'question': 'Black', 'options': ['Bianco', 'Nero', 'Arancione', 'Oro'], 'correctIndex': 1},
      {'question': 'City', 'options': ['Paese', 'Città', 'Stato', 'Via'], 'correctIndex': 1},
      {'question': 'Street', 'options': ['Piazza', 'Strada', 'Ponte', 'Prato'], 'correctIndex': 1},
      {'question': 'Car', 'options': ['Bici', 'Auto', 'Bus', 'Treno'], 'correctIndex': 1},
      {'question': 'Dog', 'options': ['Gatto', 'Cane', 'Uccello', 'Pesce'], 'correctIndex': 1},
      {'question': 'Cat', 'options': ['Cane', 'Gatto', 'Topo', 'Coniglio'], 'correctIndex': 1},
      {'question': 'Time', 'options': ['Ora', 'Tempo', 'Giorno', 'Anno'], 'correctIndex': 1},
      {'question': 'Happy', 'options': ['Triste', 'Felice', 'Arrabbiato', 'Stanco'], 'correctIndex': 1},
      {'question': 'Sad', 'options': ['Felice', 'Triste', 'Forte', 'Debole'], 'correctIndex': 1},
      {'question': 'Good', 'options': ['Cattivo', 'Buono', 'Grande', 'Piccolo'], 'correctIndex': 1},
      {'question': 'Bad', 'options': ['Buono', 'Cattivo', 'Meglio', 'Peggio'], 'correctIndex': 1},
      {'question': 'Small', 'options': ['Grande', 'Piccolo', 'Leggero', 'Corto'], 'correctIndex': 1},
      {'question': 'Big', 'options': ['Piccolo', 'Grande', 'Pesante', 'Lungo'], 'correctIndex': 1},
      {'question': 'Beautiful', 'options': ['Brutto', 'Bello', 'Giovane', 'Vecchio'], 'correctIndex': 1},
      {'question': 'Ugly', 'options': ['Bello', 'Brutto', 'Sporco', 'Pulito'], 'correctIndex': 1},
      {'question': 'Always', 'options': ['Mai', 'Sempre', 'Spesso', 'Oggi'], 'correctIndex': 1},
      {'question': 'Never', 'options': ['Sempre', 'Mai', 'Forse', 'Dopo'], 'correctIndex': 1},
      {'question': 'Please', 'options': ['Grazie', 'Per favore', 'Scusa', 'Ciao'], 'correctIndex': 1},
      {'question': 'Sorry', 'options': ['Grazie', 'Scusa/Mi dispiace', 'Ciao', 'Pardon'], 'correctIndex': 1},
      {'question': 'Goodbye', 'options': ['Ciao', 'Arrivederci', 'A dopo', 'Addio'], 'correctIndex': 1},
      {'question': 'Eat', 'options': ['Bere', 'Mangiare', 'Dormire', 'Correre'], 'correctIndex': 1},
      {'question': 'Drink', 'options': ['Mangiare', 'Bere', 'Leggere', 'Scrivere'], 'correctIndex': 1},
      {'question': 'Sleep', 'options': ['Lavorare', 'Dormire', 'Sognare', 'Alzarsi'], 'correctIndex': 1},
      {'question': 'Work', 'options': ['Gioco', 'Lavoro', 'Studio', 'Viaggio'], 'correctIndex': 1},
      {'question': 'Money', 'options': ['Oro', 'Soldi', 'Ricchezza', 'Banca'], 'correctIndex': 1},
    ],
    'Italian to English': [
      {'question': 'Ciao', 'options': ['Goodbye', 'Hello/Hi', 'Thanks', 'Please'], 'correctIndex': 1},
      {'question': 'Grazie', 'options': ['Sorry', 'Thank you', 'Welcome', 'Yes'], 'correctIndex': 1},
      {'question': 'Sì', 'options': ['No', 'Yes', 'Maybe', 'Always'], 'correctIndex': 1},
      {'question': 'No', 'options': ['Yes', 'No', 'Never', 'Today'], 'correctIndex': 1},
      {'question': 'Acqua', 'options': ['Fire', 'Water', 'Air', 'Ground'], 'correctIndex': 1},
      {'question': 'Pane', 'options': ['Milk', 'Bread', 'Pasta', 'Pizza'], 'correctIndex': 1},
      {'question': 'Amico', 'options': ['Enemy', 'Friend', 'Brother', 'Cousin'], 'correctIndex': 1},
      {'question': 'Casa', 'options': ['School', 'House', 'Car', 'Shop'], 'correctIndex': 1},
      {'question': 'Libro', 'options': ['Pen', 'Book', 'Paper', 'Bag'], 'correctIndex': 1},
      {'question': 'Sole', 'options': ['Moon', 'Sun', 'Star', 'Rain'], 'correctIndex': 1},
      {'question': 'Luna', 'options': ['Sun', 'Moon', 'Cloud', 'Planet'], 'correctIndex': 1},
      {'question': 'Giorno', 'options': ['Night', 'Day', 'Week', 'Year'], 'correctIndex': 1},
      {'question': 'Notte', 'options': ['Day', 'Night', 'Evening', 'Morning'], 'correctIndex': 1},
      {'question': 'Ragazzo', 'options': ['Girl', 'Boy', 'Man', 'Woman'], 'correctIndex': 1},
      {'question': 'Ragazza', 'options': ['Boy', 'Girl', 'Woman', 'Man'], 'correctIndex': 1},
      {'question': 'Uomo', 'options': ['Woman', 'Man', 'Father', 'Son'], 'correctIndex': 1},
      {'question': 'Donna', 'options': ['Man', 'Woman', 'Mother', 'Sister'], 'correctIndex': 1},
      {'question': 'Padre', 'options': ['Mother', 'Father', 'Uncle', 'King'], 'correctIndex': 1},
      {'question': 'Madre', 'options': ['Father', 'Mother', 'Aunt', 'Queen'], 'correctIndex': 1},
      {'question': 'Amore', 'options': ['Hate', 'Love', 'Peace', 'Heart'], 'correctIndex': 1},
      {'question': 'Vita', 'options': ['Death', 'Life', 'World', 'Time'], 'correctIndex': 1},
      {'question': 'Rosso', 'options': ['Blue', 'Red', 'Green', 'Yellow'], 'correctIndex': 1},
      {'question': 'Blu', 'options': ['Red', 'Blue', 'White', 'Black'], 'correctIndex': 1},
      {'question': 'Verde', 'options': ['Yellow', 'Green', 'Grey', 'Brown'], 'correctIndex': 1},
      {'question': 'Bianco', 'options': ['Black', 'White', 'Pink', 'Purple'], 'correctIndex': 1},
      {'question': 'Nero', 'options': ['White', 'Black', 'Orange', 'Grey'], 'correctIndex': 1},
      {'question': 'Città', 'options': ['Village', 'City', 'Country', 'Street'], 'correctIndex': 1},
      {'question': 'Strada', 'options': ['Square', 'Road/Street', 'Bridge', 'Field'], 'correctIndex': 1},
      {'question': 'Auto', 'options': ['Bike', 'Car', 'Bus', 'Train'], 'correctIndex': 1},
      {'question': 'Cane', 'options': ['Cat', 'Dog', 'Bird', 'Fish'], 'correctIndex': 1},
      {'question': 'Gatto', 'options': ['Dog', 'Cat', 'Mouse', 'Hamster'], 'correctIndex': 1},
      {'question': 'Tempo', 'options': ['Clock', 'Time', 'Weather', 'Day'], 'correctIndex': 1},
      {'question': 'Felice', 'options': ['Sad', 'Happy', 'Angry', 'Tired'], 'correctIndex': 1},
      {'question': 'Triste', 'options': ['Happy', 'Sad', 'Strong', 'Weak'], 'correctIndex': 1},
      {'question': 'Buono', 'options': ['Bad', 'Good', 'Better', 'Best'], 'correctIndex': 1},
      {'question': 'Cattivo', 'options': ['Good', 'Bad', 'Mean', 'Evil'], 'correctIndex': 1},
      {'question': 'Piccolo', 'options': ['Big', 'Small', 'Light', 'Short'], 'correctIndex': 1},
      {'question': 'Grande', 'options': ['Small', 'Big', 'Heavy', 'Long'], 'correctIndex': 1},
      {'question': 'Bello', 'options': ['Ugly', 'Beautiful', 'New', 'Old'], 'correctIndex': 1},
      {'question': 'Brutto', 'options': ['Beautiful', 'Ugly', 'Dirty', 'Clean'], 'correctIndex': 1},
      {'question': 'Sempre', 'options': ['Never', 'Always', 'Often', 'Today'], 'correctIndex': 1},
      {'question': 'Mai', 'options': ['Always', 'Never', 'Maybe', 'Soon'], 'correctIndex': 1},
      {'question': 'Per favore', 'options': ['Thanks', 'Please', 'Sorry', 'Hello'], 'correctIndex': 1},
      {'question': 'Scusa', 'options': ['Thanks', 'Excuse me/Sorry', 'Hello', 'Hi'], 'correctIndex': 1},
      {'question': 'Arrivederci', 'options': ['Hello', 'Goodbye', 'See you', 'Hi'], 'correctIndex': 1},
      {'question': 'Mangiare', 'options': ['Drink', 'Eat', 'Sleep', 'Run'], 'correctIndex': 1},
      {'question': 'Bere', 'options': ['Eat', 'Drink', 'Read', 'Write'], 'correctIndex': 1},
      {'question': 'Dormire', 'options': ['Work', 'Sleep', 'Dream', 'Rise'], 'correctIndex': 1},
      {'question': 'Lavoro', 'options': ['Play', 'Work', 'Job', 'Study'], 'correctIndex': 1},
      {'question': 'Soldi', 'options': ['Gold', 'Money', 'Coin', 'Rich'], 'correctIndex': 1},
    ],
  };

  void startQuiz(String difficulty, int totalQs) {
    selectedDifficulty.value = difficulty;
    totalQuestions.value = totalQs;
    currentStep.value = 2;
    currentQuestionIndex.value = 0;
    score.value = 0;
    isAnswered.value = false;
    selectedOption.value = -1;

    List<Map<String, dynamic>> allQuestions = List.from(questionBank[selectedLanguage.value] ?? []);

    if (allQuestions.isEmpty) {
      allQuestions = [{'question': 'Coming Soon', 'options': ['A','B','C','D'], 'correctIndex': 0}];
    }

    allQuestions.shuffle();

    if (allQuestions.length >= totalQs) {
      quizData = allQuestions.sublist(0, totalQs);
    } else {
      quizData = List.from(allQuestions);
      Random random = Random();
      while (quizData.length < totalQs) {
        quizData.add(allQuestions[random.nextInt(allQuestions.length)]);
      }
    }
  }

  void checkAnswer(int index) {
    if (isAnswered.value) return;
    selectedOption.value = index;
    isAnswered.value = true;
    if (index == quizData[currentQuestionIndex.value]['correctIndex']) {
      score.value++;
    }
  }

  void nextQuestion() {
    if (currentQuestionIndex.value < totalQuestions.value - 1) {
      currentQuestionIndex.value++;
      isAnswered.value = false;
      selectedOption.value = -1;
    } else {
      currentStep.value = 3;
      _saveScore();
    }
  }

  Future<void> _saveScore() async {
    if (score.value > 0) {
      try {
        await _firestore.collection('users').doc(_auth.currentUser!.uid).update({
          'score': FieldValue.increment(score.value),
        });
      } catch (e) {
        debugPrint("Error: $e");
      }
    }
  }

  void resetQuiz() {
    currentStep.value = 0;
    selectedLanguage.value = '';
    quizData = [];
  }
}